FROM ubuntu:22.04

# install python3
RUN apt-get update && apt-get install -y python3

# run python code directly when container starts
CMD python3 -c "def isHappy(n):\
 seen=set()\
 while n!=1 and n not in seen:\
  seen.add(n)\
  n=sum(int(d)**2 for d in str(n))\
 return n==1;\
print(19, isHappy(19));\
print(2, isHappy(2))"
